name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ZMK
        uses: zmkfirmware/zmk-build-action@v1
        with:
          zmk_version: main  # Укажи main для Studio
      - name: Build Firmware
        run: |
          west build -p -b nice_nano_v2 -- -DSHIELD=corne_left -DZMK_CONFIG=${{ github.workspace }}/config
          west build -p -b nice_nano_v2 -- -DSHIELD=corne_right -DZMK_CONFIG=${{ github.workspace }}/config
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/zephyr/zmk.uf2